server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: project-producer-technical-assignment
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topic: hotel_availability_searches

  datasource:
    url: jdbc:postgresql://localhost:5432/hotels
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


